### PR TITLE
Update hg38 data download to use curl instead of gsutil.

### PR DESCRIPTION
**Pull request by jondeaton**

### CODE REVIEW

**Review by exnx — COMMENTED** [review]
thanks for contributing! however, the curl doesn't work for me.  I get `curl: (23) Failed writing body (0 != 364)`.

**Comment by jondeaton** [comment]
Interesting, I think this error is probably coming because the `data/hg38` directory wasn't there? I fixed the `mkdir` command to use the `-p` so it correctly makes this directory. Working for me once this directory is there.

**Comment by exnx** [comment]
oh awesome, ok that worked!  I'm wondering, how does this work without having to pay for the download?  Someone is hosting it and being charged, right?

Thank you!

**Comment by jondeaton** [comment]
Good point, actually - I'm not quite sure. I found it these here: https://github.com/calico/basenji/blob/master/manuscripts/akita/tutorial.ipynb which seems to be from a Calico project.

**Pull request merged**
